### ISSUE TITLE
Vencord gets unlogged every time i close the app.

### ISSUE THREAD

**Issue by enderpuff** [Vencord/Desktop#34] opened 2023-05-16 21:43 UTC
Self explaining

**Comment by Vendicated** [comment] 2023-05-16 21:46
unlogged?

**Comment by enderpuff** [comment] 2023-05-16 21:47
My account gets logged out. That's on 0.2.0, linux client

**Comment by Vendicated** [comment] 2023-05-16 21:58
which package type did you use?

**Comment by Vendicated** [comment] 2023-05-17 01:13
that's strange, i haven't changed anything between those versions that would cause it

**Comment by enderpuff** [comment] 2023-05-21 15:14
I will close this as it seems to have stopped. I will re-open it if the issue starts appearing again

**Comment by Devetec** [comment] 2023-07-02 01:37
this keeps happening to me now...

**Comment by Vendicated** [comment] 2023-07-06 17:41
Apparently this is caused by you closing Discord via CTRL+C. Or there is an issue with Electron's data persistence. Observe the console for errors and try reinstalling

**Comment by enderpuff** [comment] 2023-07-06 17:41
The issue seems to be happening again on 0.2.6 for me. It only unlogs my main account, though, my secondary stays logged for some reason

**Closed by Vendicated** 2023-07-06 17:41 UTC

**Comment by Devetec** [comment] 2023-07-09 22:50
> Apparently this is caused by you closing Discord via CTRL+C. Or there is an issue with Electron's data persistence. Observe the console for errors and try reinstalling
> 
> Closing as wontfix because this is not under our control

@Vendicated It isn't due to closing Discord with CTRL+C.
I was able to reproduce this by adding another Discord account to Vencord and then closing it with the "x" in the top-right corner. When reopening the app, the first Discord account will have been logged-out of, and it will prompt you to choose to log into the second Discord account.
